config/routes.rb
Minecamp::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '' => 'main#index'
  resources :users
  resources :auth
  resource :info, controller: "info"
  resources :battles

  resources :battle_results do
    collection do
      get :test
    end
  end

  

end

app/models/battle.rb
class Battle < ActiveRecord::Base
  
  def close
    self.status = 1
  end
  
  def is_closed?
    self.status == 1
  end
  
  has_many :battle_results
  belongs_to :admin, foreign_key: "user_id", class_name: "User"
  
end

app/models/battle_result.rb
class BattleResult < ActiveRecord::Base
  belongs_to :battle
  belongs_to :user
end

app/models/cube.rb
class Cube < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/loot.rb
class Loot < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, length: {minimum: 3, maximum: 20},
                   uniqueness: {case_sensitive: false},
                   if: :name
  validates :email, format: /\w+@\w+/,#email: true,
                    uniqueness: {case_sensitive: false},
                    if: :email
  validates :password, length: {minimum: 5, maximum:20}
  
  #has_one :player
  has_many :battles
  
#  def admin?
#    false
#  end
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
end

app/models/weapon_origin.rb
class WeaponOrigin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  
  before_action :get_sess_id
  #before_action :require_login#, only: [:show]
  
  
  def get_sess_id
    @sess_id = params[:sess_id]
    @current_user = User.where(sess_id: @sess_id).first if @sess_id else nil
  end
  
  def require_login
    #get_sess_id()
    respond_to do |format|
      format.html do
        unless @current_user
          #redirect_to action: "user#index"
          render text: "not authenticated"
          return
        end
      end
      format.json do
        unless @current_user
          render text: '{"error": "not authenticated"}'
          return
        end
      end
    end
  end
  
  def get_new_sess_id
    rand.to_s#"The Very Random Token "+
  end
  
  def login(user)
    @sess_id = get_new_sess_id
    @current_user = user
    user.sess_id = @sess_id
    user.save()
  end
  
#  def current_user
#    @current_user = User.find(1)
#  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  
  def new
    
  end
  
  def create
    par = params[:user]
    @error = nil
    @user = User.where(name: par[:name]).first
    if @user
      if @user.password != par[:password]
      then @error = "Wrong password"
      else login @user end
    else
      @error = "No such user"
    end
    
    
    respond_to do |format|
      format.html {
        unless @error
          redirect_to '/?sess_id='+@sess_id
        else
          render action: "new"
        end
      }
      format.json {
        unless @error
          render json: { id: @current_user.id, sess_id: @sess_id }
        else
          render json: { error: @error }
        end
      }
    end
  end
  
end

app/controllers/battle_results_controller.rb
class BattleResultsController < ApplicationController
  require 'redis'

  before_action :require_login, only: [:create]
  
  def initialize
    @redis = Redis.new
  end

  def test
    #render text: 'test'
  end
  
  def index
    if uid = params["user"]
      @user = User.find(uid)
      @battle_results = BattleResult.joins(:user).where({ user: @user }).all()
    else
      @battle_results = BattleResult.all()
    end
  end
  
  def create
    if not battle_id = params["id"]
      error = "no battle id"
    elsif not battle = Battle.where(id: battle_id).first
      error = "no battle with id="+battle_id
    elsif @current_user != battle.admin
      error = "you are not battle creator"
    elsif battle.is_closed?
      error = "battle already closed"
#    elsif amount = params["amount"] #user sended info about self
#      BattleResult.create(
#        battle_id: battle_id,
#        user_id: @current_user.id,
#        chips: amount
#      )
    else #received user array
      error = ""
      
      battle.close
      battle.save
      
      params.each do |uname,amount|
        unless uname.starts_with? "user" then next end
        uid = uname[4..-1]
        p uid, amount
        BattleResult.create(
          battle_id: battle_id,
          user_id: uid,
          chips: amount
        )
        u = User.find(uid)
        u.chips += amount
        u.save()
      end
    end
    respond_to do |format|
      format.json do
        render json: {error: error}
      end
    end
  end
  
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :require_login, only: [:create]
  
  def index
    
  end
  
  def create
    b = Battle.create(admin: @current_user)
    respond_to do |format|
      format.json { render json: {id: b.id} }
    end
  end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  before_action :require_login#, only: [:show]
  
  def show
    respond_to do |format|
      format.json do
        @user_data = @current_user.serializable_hash.except("password", "sess_id")
        render json: @user_data
      end
    end
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @hello_text = "Hello!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    respond_to do |format|
      @user = User.find(params[:id])
      format.html
      format.json { render :json => { id: @user.id, name: @user.name } }
      #render json: @statuses.select([:latitude, :longitude, :timestamp, :virtual_odometer])
    end
  end
  
  
  def create
    @user = User.new(params[:user].permit(:name, :email, :password))
    respond_to do |format|
      format.html do
        if @user.save
          login @user
          redirect_to '/?sess_id='+@sess_id
        else
          render action: "new"
        end
      end
      format.json do
        if @user.save
          login @user
          render json: { id: @current_user.id, sess_id: @sess_id }
        else
          render json: @user.errors.messages
        end
      end
    end
  end
  
  def new
    @user = User.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_sess_id body, url, *args
    if @sess_id
      url += (url.index("?") ? "&sess_id=" : "?sess_id=") + @sess_id
    end
    link_to body, url, *args #response.body
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/battle_results/index.html.erb
<h3>Результаты боев 
<% if @user %>
  пользователя <%= @user.name %> 
<% end %>
:</h3>
<table border="1" cellspacing="1">
<thead><td>id</td> <td>battle id</td> <td>user id</td> <td>chips</td></thead>
<% @battle_results.each do |br| %>
<tr>
	<td><%= br.id %></td>
	<td><%= br.battle_id %></td>
	<td><%= br.user_id %></td>
	<td><%= br.chips %></td>
</tr>
<% end %>
</table><br>

<!--table border="1" cellspacing="1">
<thead><td>user</td> <td>chips</td></thead>
<% @redis.keys("user:*").each do |key| %>
<tr><td><%= key %></td><td><%= @redis.get(key) %></td></tr>
<% end%>
</table-->

app/views/battle_results/test.html.erb
<h3>Результаты боев 
<% if @user %>
  пользователя <%= @user.name %> 
<% end %>
:</h3>
<table border="1" cellspacing="1">
<thead><td>id</td> <td>battle id</td> <td>user id</td> <td>chips</td></thead>
</table><br>

<!--table border="1" cellspacing="1">
<thead><td>user</td> <td>chips</td></thead>
<% @redis.keys("user:*").each do |key| %>
<tr><td><%= key %></td><td><%= @redis.get(key) %></td></tr>
<% end%>
</table-->

app/views/battles/index.html.erb
<h2>Эпически информативная страница</h2>
<h3>users:</h3>
<table border="1" cellspacing="1">
<thead><td>id</td> <td>name</td> <td>email</td> <td>password</td> <td>sess id</td></thead>
<% User.all.each do |u| %>
<tr>
	<td><%= u.id %></td>
	<td><%= u.name %></td>
	<td><%= u.email %></td>
	<td><%= u.password %></td>
	<td><%= u.sess_id %></td>
</tr>
<% end %>
</table><br>

<h3>battles:</h3>
<table border="1" cellspacing="1">
<tr><td>id</td><% Battle.all.each do |b| %><td><%= b.id %></td><% end %></tr>
<tr><td><u>O</u>pened/<u>C</u>losed</td><% Battle.all.each do |b| %><td><%= b.status==1?"c":"o" %></td><% end %></tr>
</table><br>

<h3>battle results:</h3>
<table border="1" cellspacing="1">
<thead><td>id</td> <td>battle id</td> <td>user id</td> <td>chips</td></thead>
<% BattleResult.all.each do |br| %>
<tr>
	<td><%= br.id %></td>
	<td><%= br.battle_id %></td>
	<td><%= br.user_id %></td>
	<td><%= br.chips %></td>
</tr>
<% end %>
</table><br>

<hr>

<h3>Создание боя</h3>
Всё просто: <b>POST</b> на адрес, который в кнопке.<br>
В ответ - айди нового боя. Что-то типа <b>{"id": 5}</b>.<br>
<button id="battle_send_button" onclick="send(battle_dest_url, null)"></button><br>
*само не обновляется, жать F5*<br><br>


<h3>Создание результатов боя</h3>
Отправка результатов о бое с id=1 для юзеров 1 и 2, собравших 10 и 20 чипов соответственно.<br>
Можно <a href="javascript:result_multi.value='id=1&amount=30'">послать инфу о себе</a>.<br>
(уже нельзя. но можно раскомментировать кусок в battle_resilts_controller.rb)<br>
Содержимое этого поля шлётся просто как текст <b>POST</b>'ом.<br>
Возвращает <b>{"error": "error_text"}</b>, текст: "no battle id", или "no battle with id=&lt;id&gt;", или "" (когда всё ОК).<br>
<textarea id="result_multi" rows="2" cols="96"></textarea><br>
<button id="result_send_button" onclick="send(result_dest_url, result_multi.value)"></button><br>
*само не обновляется, жать F5*<br><br>


<h3>А ещё...</h3>
А ещё можно (и нужно) в процессе боя слать информацию о собранном по <b>UDP</b> на <b>3001й</b> порт.<br>
Слать в виде <b>uid:amount:sess_id.</b><br>
Например <b>1:10:0.235346234235</b>, т.е. юзер с id=1 собрал 10 чипов.<br>
Айди боя, к сожалению, пока в результатах не учитывается. Просто сумма по всем.<br>
Если получися успешно отправить, <a href="/battle_results">тут</a> будет списочек результатов.<br>
Примерно так в Юнити шёлтся UDP:
<pre>
using System.Net.Sockets;
remoteEndPoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 3001);
client = new UdpClient();
byte[] data = Encoding.UTF8.GetBytes(text);
client.Send(data, data.Length, remoteEndPoint);
</pre>

<script>
sess_id = document.URL.match(/\?.*/)[0];

battle_dest_url = "/battles.json"+sess_id;
battle_send_button.innerHTML = "заPOSTить на <b>"+battle_dest_url+"</b>";

result_dest_url = "/battle_results.json"+sess_id;
result_send_button.innerHTML = "заPOSTить на <b>"+result_dest_url+"</b>";
result_multi.value = "id=1&user1=10&user2=20";

function send(url, data) {
	var xhr = new XMLHttpRequest();
	xhr.open('POST', url, false);
	xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
	xhr.send(data);
	if (xhr.status == 200)
		alert(xhr.responseText);
	else
		document.body.outerHTML = xhr.responseText;
}
</script>

app/views/info/show.html.erb
Hello, it's auth index.<br>
<% @user_data.each do |k,v| %>
	<b><%= k %>:</b> <%= v %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minecamp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
    <!--div class="navbar navbar navbar-inverse navbar-fixed-top"-->
        <div class="navbar-inner">
            <div class="container">
            <a class="brand" href="/">Minecamp</a>
            <ul class="nav">
                <li><a href="/users">Пользователи</a></li>
                <li><a href="/battles">Бои</a></li>
                <li><a href="/battle_results">Результаты боев</a></li>
            </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <%= yield %>
    </div>

</body>
</html>

app/views/main/index.html.erb
<div>-<%= @hello_text %>-</div>
<%= link_to_sess_id "admin page", "/admin" %>

app/views/users/index.html.erb
<table border="1" cellspacing="0">
<thead>
    <th>Name</th> 
    <th>добавлен</th>
    <th></th>
</thead>
<% @users.each do |u| %>
    <tr><td><%= u.name %></td>
    <td><%= u.created_at %></td>
    <td><%= link_to "Результаты боев", battle_results_path(:user => u.id), { :class => "btn" } %></td>
<% end %>
</table><br>


<!--<% @users.each do |u| %>
Id <%= u.id %>: <%= u.name %> - <%= u.created_at %><%= link_to "Battle results", battle_results_path(:user => u.id) %><br>
<% end %>-->

app/views/users/new.html.erb
<!--create {|a| a.to_s}= @user.errors.messages %-->
<% if @user.errors %>
    <% for message in @user.errors.full_messages %>
        <li style="color: red"><%= message %></li>
    <% end %>
<% end %>

<%= form_for :user, url: {action: 'create'} do |u| %>
<%= u.text_field :name, placeholder: 'имя' %>
<%= u.text_field :email, placeholder: 'мыло' %>
<%= u.password_field :password, placeholder: 'пароль' %>
<%= u.submit "Ok", :class => "btn" %>
<% end %>


<button class="btn" onclick="send()">send to /users.json</button>
<script>
function send() {
	var xhr = new XMLHttpRequest();
	xhr.open('POST', '/users.json', false);
	xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
	xhr.send("user[name]="+user_name.value+"&user[email]="+user_email.value+"&user[password]="+user_password.value);
	alert("status: "+xhr.status+"\nresponse:\n"+xhr.responseText);
	//document.body.outerHTML = xhr.responseText;
}
</script>

app/views/users/show.html.erb
Это <b>show.html.erb</b><br>
<b><%= @user.id =%>:</b> <%= @user.name =%>